In [31]:
import pandas as pd

In [64]:
data = pd.DataFrame({'id':[1000, 1001, 1234, 1254, 1237, 1212, 1211, 1111, 1892, 8901, 8902], 
                     'recent':[2, 3,    4,   28,   29,  201,  205,  300,  301, 600, 601]})

In [65]:
data

      id  recent
0   1000       2
1   1001       3
2   1234       4
3   1254      28
4   1237      29
5   1212     201
6   1211     205
7   1111     300
8   1892     301
9   8901     600
10  8902     601

In [66]:
r = list(range(5, 0, -1))
recency_quartiles = pd.qcut(data['recent'], q = 5, labels=r )

In [67]:
recency_quartiles

0     5
1     5
2     5
3     4
4     4
5     3
6     3
7     2
8     2
9     1
10    1
Name: recent, dtype: category
Categories (5, int64): [5 < 4 < 3 < 2 < 1]

In [68]:
data['recency_quartile'] = recency_quartiles

In [69]:

data

      id  recent recency_quartile
0   1000       2                5
1   1001       3                5
2   1234       4                5
3   1254      28                4
4   1237      29                4
5   1212     201                3
6   1211     205                3
7   1111     300                2
8   1892     301                2
9   8901     600                1
10  8902     601                1

In [70]:
# building real lables
labels = ['active', 'lapsed', 'inactive', 'chuned', 'dead']
recency_quartiles = pd.qcut(data['recent'], q = 5, labels=labels)
data['recency_quartile_labels'] = recency_quartiles

In [71]:
data.sort_values('recency_quartile')

      id  recent recency_quartile recency_quartile_labels
0   1000       2                5                  active
1   1001       3                5                  active
2   1234       4                5                  active
3   1254      28                4                  lapsed
4   1237      29                4                  lapsed
5   1212     201                3                inactive
6   1211     205                3                inactive
7   1111     300                2                  chuned
8   1892     301                2                  chuned
9   8901     600                1                    dead
10  8902     601                1                    dead