In [8]:
import pandas as pd

In [9]:
dati = pd.read_excel("dati/ElettronicaConsumo_2fogli.xlsx")

In [14]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

In [15]:
dati

               Product   Price
0     Desktop Computer   700.0
1               Tablet   250.0
2              iPhone8   800.0
3               Laptop  1200.0
4             iPhone10  1200.0
5               Huawei   900.0
6  Auricolare Wireless   150.0

In [16]:
dati_f2 = pd.read_excel("dati/ElettronicaConsumo_2fogli.xlsx", sheet_name = "Foglio2")

In [5]:
dati_f2

      Product  Price
0       Pants  100.0
1      Jacket  250.0
2     T-shirt   80.0
3       Skirt  120.0
4   Pull-over  125.0
5       Shoes  190.0
6  Nightshirt   50.0

In [6]:
dati_f1 = pd.read_excel("dati/ElettronicaConsumo_2fogli.xlsx", sheet_name = 0)
dati_f1

               Product   Price
0     Desktop Computer   700.0
1               Tablet   250.0
2              iPhone8   800.0
3               Laptop  1200.0
4             iPhone10  1200.0
5               Huawei   900.0
6  Auricolare Wireless   150.0

In [7]:
for i in range(2):
    dati_f2 = pd.read_excel("dati/ElettronicaConsumo_2fogli.xlsx", sheet_name = i)
    print(dati_f2)

               Product   Price
0     Desktop Computer   700.0
1               Tablet   250.0
2              iPhone8   800.0
3               Laptop  1200.0
4             iPhone10  1200.0
5               Huawei   900.0
6  Auricolare Wireless   150.0
      Product  Price
0       Pants  100.0
1      Jacket  250.0
2     T-shirt   80.0
3       Skirt  120.0
4   Pull-over  125.0
5       Shoes  190.0
6  Nightshirt   50.0