In [2]:
from sklearn_extra.cluster import KMedoids
import pandas as pd

In [23]:
data = pd.DataFrame({"x": [2, 3, 4, 10, 11, 20, 222], 
                    "y":  [1, 2, 1, 17, 18, 29, 282]})

In [24]:
data

     x    y
0    2    1
1    3    2
2    4    1
3   10   17
4   11   18
5   20   29
6  222  282

In [30]:
kmedoids = KMedoids(n_clusters=4)
kmedoids.fit(data)

KMedoids(n_clusters=4)

In [31]:
kmedoids.labels_

array([2, 2, 3, 0, 0, 1, 1])

In [32]:
kmedoids.cluster_centers_

array([[10, 17],
       [20, 29],
       [ 3,  2],
       [ 4,  1]])

In [33]:
kmedoids.predict([[0,0], [4,4]])

array([2, 2])

In [34]:
kmedoids.inertia_

326.57678619394676

In [35]:
labels = list(kmedoids.labels_)

In [36]:
data["lables"] = labels

In [37]:
data

     x    y  lables
0    2    1       2
1    3    2       2
2    4    1       3
3   10   17       0
4   11   18       0
5   20   29       1
6  222  282       1